### ISSUE TITLE
QASubmission requires entityid

### ISSUE THREAD

**Issue by creotutar** [yext/answers-search-ui#352]
**Problem**
QASubmission requires entityId while the docs say that this is an optional field. Would expect QASubmission to work with only the required container config option

> Error: `entityId` is a required configuration option for Question Submission

(Aside, if a string is passed for entityId, this is not registered as an entityId and we get the same error)

**Environment**
Testing on v0.9.2 on oobx testing on Chrome Version 77.0.3865.120 (Official Build) (64-bit) with the scripts

```
<link rel="stylesheet" href="https://assets.sitescdn.net/answers/v0.9.2/answers.css">
<script src="https://assets.sitescdn.net/answers/v0.9.2/answers.js" onload="initAnswers()" async defer></script>
```

and the component config

```
                this.addComponent('QASubmission', {
                  container: '#js-form',
                  nameLabel: 'Your Name:',             // Optional, defaults to 'Name:'
                  emailLabel: '*Email:',               // Optional, defaults to '*Email:'
                  questionLabel: 'Ask us anything!:',  // Optional, defaults to 'What is your question?'
                  privacyPolicyLabel: 'I agree!',      // Optional, defaults to 'I agree to our policy:',
                  buttonLabel: 'Submit',               // Optional, defaults to 'Submit:'
                  entityId: 123,                       // Optional, the entity identifier that the question is associated with
                  language: 'en_GB',                      // Optional, defaults to 'EN'
                  formSelector: '#js-form'             // Optional, defaults to native form node within container
                });
```

**Comment by b1lly** [comment]
This is actually a required field, not optional.

The documentation is wrong. We will update.

There is a seperate request to make entity ID support strings and not just numbers. I actually have a local change that updates this.

**Comment by rosiegrant** [comment]
this is fixed in 0.9.4 (I have verified)!

**Comment by Mxs2019** [comment]
The readme is still not updated in 10.0. It still says optional. Also it says `entityIDL` instead of `entityID:`

**Comment by rosiegrant** [comment]
reopening this per max's comment above

**Comment by vramesh1** [comment]
This has been fixed in branch v0.10.1.
See updated README here :
https://github.com/yext/answers/tree/v0.10.1#qa-submission-component

The README in the master branch will be updated when the next release is cut.

Closing this issue.
